const fs = require('node:fs');
const assert = require('node:assert/strict');
const html = fs.readFileSync('vocabulary_app.html', 'utf8');
const start = html.indexOf('cloudProgressWriteTimerRef.current = setTimeout(async () => {');
const end = html.indexOf('}, 600);', start);
assert.ok(start > 0 && end > start);
const callback = html.slice(start, end);
assert.ok(callback.includes('syncInFlightRef.current'), 'Cloud writes must serialize');
assert.ok(callback.includes('syncLearningOutbox'), 'All cloud writes use transactional event journal RPC');
assert.ok(callback.includes('syncAccountRef.current !== accountId'), 'Account changes prevent cross-account requests');
assert.ok(!callback.includes('.upsert('), 'No client read-modify-write snapshot upsert');
assert.ok(!callback.includes('Math.max('), 'Server response counters are authoritative');
assert.ok(callback.includes('catch (error)'), 'All failed writes remain visible and retryable');
assert.ok(html.includes("window.addEventListener('online', retry)"));
assert.ok(html.includes("document.addEventListener('visibilitychange', retry)"));
assert.ok(html.includes('setInterval(retry, 15000)'));
console.log('PASS: cloud sync uses serialized journal RPC, authoritative response, account gate and explicit automatic retries');
